[package]
name = "CliNotes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = {version = "0.29.0", features = ["chrono"]}
chrono = "0.4.28"
clap = "2.21.1"
